server:
  port: 8088
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
#      包含副本的写法
      uri: mongodb://192.168.0.180:27017,192.168.0.180:27018,192.168.0.180:27019/articledb?connect=replicaSet&secondaryOk=true&replicaSet=myrs
#      单机的写法
#      host: 192.168.0.180
#      port: 27017
#      database: articledb