@hostname = 192.168.0.193
@port=18083
@contentType=application/json
@userName=admin
@password=public

#############查看已有用户认证数据##############
GET http://{{hostname}}:{{port}}/api/v4/auth_username HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic {{userName}}:{{password}}


########添加用户认证数据##############
POST http://{{hostname}}:{{port}}/api/v4/auth_username HTTP/1.1
Content-Type:{{contentType}}
Authorization:Basic {{userName}}:{{password}}

{
"username": "chendom",
"password": "chendom@123"
}


###########更改指定用户名的密码#############
PUT http://{{hostname}}:{{port}}/api/v4/auth_username/chendom HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic {{userName}}:{{password}}

{
"password": "chendom@123"
}

###########查看指定用户名信息#############
GET http://{{hostname}}:{{port}}/api/v4/auth_username/chendom HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic {{userName}}:{{password}}

###########删除指定的用户信息#############
DELETE http://{{hostname}}:{{port}}/api/v4/auth_username/chendom HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic {{userName}}:{{password}}
